"use strict";

const fs = require("fs");
const path = require("path");
const os = require("os");

/**
 * Windsurf (Codeium's AI IDE) Cascade agent conversation history.
 *
 * VERIFICATION STATUS (read this before trusting anything below):
 * multi-source-corroborated-but-UNVERIFIED. Windsurf is not installed on
 * the machine this adapter was built on (checked: no /Applications/Windsurf.app,
 * no ~/.codeium, no ~/Library/Application Support/Windsurf, no ~/.windsurf,
 * no ~/.config/Windsurf) — there was no real install available to confirm
 * this against, unlike claude-code.js. Treat findings from this source with
 * that in mind until someone with Windsurf installed confirms it against
 * real data (see CONTRIBUTING.md).
 *
 * Windsurf is a VS Code fork, but — deliberately verified rather than
 * assumed, per this adapter's brief — its Cascade conversation history is
 * NOT stored the way Cursor's chat/composer data is (VS Code's per-profile
 * `state.vscdb` SQLite file). Instead, Cascade keeps its own store, separate
 * from the standard VS Code `User/globalStorage` directory entirely:
 *
 *   ~/.codeium/windsurf/cascade/**\/*.pb    — Cascade conversation history
 *   ~/.codeium/windsurf/memories/**\/*.pb   — Cascade's auto-generated
 *                                             per-workspace memories (also
 *                                             user-authored/session-derived
 *                                             content, same store convention)
 *
 * identically on macOS and Linux (NOT XDG_CONFIG_HOME-aware — every source
 * below agrees on the literal `~/.codeium/windsurf/...` path on both OSes,
 * consistent with `~/.codeium/` predating Windsurf-the-IDE as Codeium's one
 * shared per-user directory across all its editor plugins), and at
 * `%USERPROFILE%\.codeium\windsurf\...` on Windows.
 *
 * Sources cross-checked (2026-09), most authoritative first:
 *  1. Official docs — https://docs.windsurf.com/windsurf/cascade/memories
 *     redirects (307, Windsurf/Codeium having been folded into Cognition's
 *     Devin product line) to https://docs.devin.ai/desktop/cascade/memories,
 *     which states verbatim: "Cascade's autogenerated memories are
 *     associated with the workspace they were created in and are stored
 *     locally in `~/.codeium/windsurf/memories/`."
 *  2. github.com/1837620622/devin-tools (fix-devin-mac.sh, formerly a
 *     Windsurf-focused maintenance script, still shipping fix-windsurf-*.sh
 *     entry points) — a real, detailed cleanup/repair tool that treats
 *     `~/.codeium/windsurf/cascade/*.pb` as conversation history it must
 *     explicitly avoid deleting outside an opt-in "wipe Cascade" mode, and
 *     separately globs `memories/*.pb`. Also independently confirms VS
 *     Code's own `User/globalStorage/state.vscdb` exists in Windsurf's
 *     *application-support* directory as a distinct thing it reports the
 *     size of but never treats as chat storage — corroborating the split
 *     from Cascade's own `~/.codeium/windsurf/` store.
 *  3. iamraghuveer.com/posts/windsurf-team-shared-memory — an independent
 *     write-up confirming memories live under `~/.codeium/windsurf/memories/`,
 *     keyed by a hash of the workspace path (hence this adapter walking
 *     that directory recursively rather than assuming a flat file list).
 *  4. A Medium "Windsurf Internals" piece that mitmproxy'd Windsurf's own
 *     traffic and found its backend RPCs are literally named things like
 *     `exa.api_server_pb.ApiServerService/...` — corroborating (not proving)
 *     that Windsurf's client is built around protobuf end to end, which is
 *     what `.pb`-suffixed local cache files would be.
 *
 * What this adapter deliberately does NOT include: the `state.vscdb`-based
 * approach some community MCP tools (e.g. a `windsurf-reader.ts` found on
 * npm/GitHub) take, reading VS Code's `ItemTable` for keys like
 * `cascade.chatdata`. That reader's own header says it "parses SQLite
 * database similar to Cursor" — phrasing that reads as an assumption, not
 * independent verification — and a sibling tool's Windsurf extractor reuses
 * the literal table name `cursorDiskKV` (Cursor's own internal name) for
 * Windsurf, which is implausible as Windsurf's own schema and looks like
 * uncritical copy-paste from Cursor's adapter rather than a checked fact.
 * Shipping that guess would risk exactly the "checks the wrong place,
 * reports clean" failure this project exists to avoid. If a future
 * contributor confirms real chat content actually lives in Windsurf's
 * state.vscdb too, add it then — with that verification.
 *
 * The internal byte layout of a `.pb` file is unverified (no accessible
 * .proto schema was found) and is NOT relied on here — same tolerance
 * cursor.js documents for opaque SQLite blob values: this scanner matches
 * raw text regardless of the structure it came from. A `.pb` file's bytes
 * are decoded 1:1 via "latin1" (no lossy re-encoding, unlike "utf-8" on
 * non-UTF-8 binary) and treated as one long scannable string, protobuf's
 * wire format stores string/bytes field values as raw, unmodified bytes, so
 * a leaked secret embedded in one is still present, contiguous, and
 * pattern-matchable in that string — the same reasoning that lets `strings`
 * find text inside arbitrary binaries.
 */
function windsurfRoot() {
  const home = os.homedir();
  if (process.platform === "win32") {
    const userProfile = process.env.USERPROFILE || home;
    return path.join(userProfile, ".codeium", "windsurf");
  }
  // macOS and Linux: identical, non-XDG-aware path — see the sources above.
  return path.join(home, ".codeium", "windsurf");
}

const ROOT = windsurfRoot();

// The two subdirectories confirmed (see docstring) to hold Cascade
// conversation-derived `.pb` content. Order doesn't matter; both are walked.
const SUBDIRS = ["cascade", "memories"];

// Bounds for readLines(). No real `.pb` file has been observed (no real
// install to observe one against) — this reuses claude-code.js's generous
// 2GB backstop rather than inventing a number with no evidence behind it.
const MAX_BYTES = 2 * 1024 * 1024 * 1024;
const READ_TIMEOUT_MS = 60_000;

// Recursion guard for walking cascade/memories — memories is documented to
// nest by a per-workspace hash (see source 3 above); depth is capped, and
// symlinked subdirectories are de-duped by real path, purely to bound a
// pathological or cyclic layout rather than because deep nesting is expected.
const MAX_WALK_DEPTH = 12;

function id() { return "windsurf"; }
function label() { return "Windsurf"; }

function available() {
  try { return fs.statSync(ROOT).isDirectory(); } catch { return false; }
}

/**
 * Same defensive symlink-following convention as claude-code.js's
 * isDirFollowingSymlink (see that file for the full reasoning) — Dirent
 * reflects lstat semantics, so a symlinked cascade/memories directory (or a
 * symlinked file inside one) must be resolved explicitly or it is silently
 * excluded.
 */
function isKindFollowingSymlink(fullPath, dirent, checkFn) {
  if (checkFn(dirent)) return true;
  if (!dirent.isSymbolicLink()) return false;
  try { return checkFn(fs.statSync(fullPath)); } catch { return false; }
}
const isDirFollowingSymlink = (p, d) => isKindFollowingSymlink(p, d, (x) => x.isDirectory());
const isFileFollowingSymlink = (p, d) => isKindFollowingSymlink(p, d, (x) => x.isFile());

/**
 * Recursively yield { file, mtimeMs, sizeBytes, broken } for every `*.pb`
 * file under `dir`. A dangling symlink (file or directory) is reported
 * broken:true rather than silently skipped, matching claude-code.js's
 * convention. `visitedRealDirs` de-dupes symlinked directories by resolved
 * real path so a symlink cycle terminates instead of recursing forever.
 */
function* walkPbFiles(dir, depth, visitedRealDirs) {
  if (depth > MAX_WALK_DEPTH) return;

  let entries;
  try { entries = fs.readdirSync(dir, { withFileTypes: true }); }
  catch { yield { file: dir, broken: true }; return; }

  for (const e of entries) {
    const full = path.join(dir, e.name);

    if (isDirFollowingSymlink(full, e)) {
      if (e.isSymbolicLink()) {
        let real;
        try { real = fs.realpathSync(full); }
        catch { yield { file: full, broken: true }; continue; }
        if (visitedRealDirs.has(real)) continue;
        visitedRealDirs.add(real);
      }
      yield* walkPbFiles(full, depth + 1, visitedRealDirs);
      continue;
    }

    if (!e.name.endsWith(".pb")) continue;

    if (!isFileFollowingSymlink(full, e)) {
      if (e.isSymbolicLink()) yield { file: full, broken: true };
      continue;
    }

    let stat;
    try { stat = fs.statSync(full); } catch { yield { file: full, broken: true }; continue; }
    yield { file: full, mtimeMs: stat.mtimeMs, sizeBytes: stat.size, broken: false };
  }
}

/**
 * Yield { file, mtimeMs, sizeBytes, broken } for every `.pb` file under
 * ~/.codeium/windsurf/cascade and ~/.codeium/windsurf/memories.
 *
 * A subdirectory that simply doesn't exist (e.g. a user who has never
 * triggered an auto-generated memory) yields nothing for it — normal, not
 * broken, same convention as cursor.js's statIfPresent. Only an entry that
 * looked like it should resolve and didn't (chiefly a dangling symlink) is
 * reported broken.
 */
function* files() {
  for (const sub of SUBDIRS) {
    const dir = path.join(ROOT, sub);

    let lst;
    try { lst = fs.lstatSync(dir); }
    catch { continue; } // not present — unremarkable, nothing to report

    if (lst.isSymbolicLink()) {
      let resolved;
      try { resolved = fs.statSync(dir); }
      catch { yield { file: dir, broken: true }; continue; }
      if (!resolved.isDirectory()) continue; // symlink resolves, but not to a directory — out of scope
    } else if (!lst.isDirectory()) {
      continue; // something unexpected sits at this path — out of scope, not broken
    }

    yield* walkPbFiles(dir, 0, new Set());
  }
}

/**
 * Read one `.pb` file as a single-element `lines` array (the whole file,
 * decoded via latin1 for a lossless byte<->char mapping — see the module
 * docstring for why splitting on embedded newline bytes is deliberately
 * NOT done here: an incidental 0x0A inside the binary encoding must not be
 * allowed to sever a secret string that happens to straddle it).
 *
 * Streamed and bounded exactly like claude-code.js's readLines(): a size
 * cap (MAX_BYTES) checked before opening, and a read timeout enforced by
 * destroying the stream, since Node's stream/readline stack has no built-in
 * one. Returns { lines, status, bytesRead } with the same status vocabulary
 * ("complete" | "partial" | "too-large" | "failed") and the same rule: any
 * bytes that WERE read before a failure are still real content and are
 * still returned, never discarded just because the read didn't finish
 * cleanly.
 */
async function readLines(file) {
  let stat;
  try { stat = fs.statSync(file); }
  catch { return { lines: [], status: "failed", bytesRead: 0 }; }
  if (stat.size > MAX_BYTES) return { lines: [], status: "too-large", bytesRead: 0 };

  const chunks = [];
  let bytesRead = 0;
  const stream = fs.createReadStream(file);
  const timer = setTimeout(() => stream.destroy(new Error("read timed out")), READ_TIMEOUT_MS);

  try {
    for await (const chunk of stream) {
      chunks.push(chunk);
      bytesRead += chunk.length;
    }
    const text = Buffer.concat(chunks).toString("latin1");
    return { lines: text.length > 0 ? [text] : [], status: "complete", bytesRead };
  } catch {
    if (chunks.length === 0) return { lines: [], status: "failed", bytesRead };
    const text = Buffer.concat(chunks).toString("latin1");
    return { lines: [text], status: "partial", bytesRead };
  } finally {
    clearTimeout(timer);
    stream.destroy();
  }
}

module.exports = { id, label, available, files, readLines };
